on: [push, pull_request]

# hello

jobs:
  call-get-changed-files:
    uses: salt-extensions/central-artifacts/.github/workflows/get-changed-files.yml@main

  call-pre-commit-action:
    uses: salt-extensions/central-artifacts/.github/workflows/pre-commit-action.yml@main
    needs:
      - call-get-changed-files
    with:
      changed-files: ${{ needs.call-get-changed-files.outputs.changed-files }}
